spring:
  application:
    name: company
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/companydb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"
