spring:
  application:
    name: department
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3399/departmentdb
#    url: jdbc:mysql://localhost:3306/departmentdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  sql:
    init:
      mode: always

  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "department"
    desctiption: "Training Tracker Department Microservice"
    version: "1.0.0"
logging:
  level:
    com:
      example:
        department: debug

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 100
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 2
# Particular Exceptions can be ignored
      ignore-exceptions:
        - java.lang.NullPointerException
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeout-duration: 1000
      limit-refresh-period: 5000
      limit-for-period: 1
      